
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/audio:/app/audio
      - ./backend/transcripts:/app/transcripts
    environment:
      - PYTHONUNBUFFERED=1
    platform: linux/amd64
    tty: true
    stdin_open: true